name: Build Windows Qt5 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (MSVC2019, modules default)
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_msvc2019_64

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with qmake & nmake
        run: |
          qmake m3.pro
          nmake

      - name: Archive Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: m3-win-binary
          path: |
            release\*.exe
            *.exe
