name: Build Windows Qt5 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (MinGW)
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_mingw81
          cache: true

      - name: Clean build artifacts
        shell: bash
        run: |
          rm -f ui_*.h
          rm -f Makefile*
          rm -rf release

      - name: Generate all UI headers
        shell: bash
        run: |
          uic editcountry.ui -o ui_editcountry.h
          uic editcur.ui -o ui_editcur.h
          uic editprv.ui -o ui_editprv.h
          uic editrec.ui -o ui_editrec.h
          uic errbase.ui -o ui_errbase.h
          uic mainwindow.ui -o ui_mainwindow.h
          uic messageslist.ui -o ui_messageslist.h
          uic setup.ui -o ui_setup.h

      - name: Build with qmake & mingw32-make
        shell: bash
        run: |
          qmake m1.pro
          mingw32-make release

      - name: Deploy Qt DLLs
        shell: bash
        run: |
          windeployqt release/m1.exe

      - name: Archive Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: m1-win-binary
          path: |
            release/*
