name: Build Windows Qt5 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (MinGW)
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_mingw81
          cache: true

      - name: List Qt include folders (diagnostics)
        shell: cmd
        run: |
          dir D:\a\remind\Qt\5.15.2\mingw81_64\include
          dir D:\a\remind\Qt\5.15.2\mingw81_64\include\QtWidgets

      - name: Build with qmake & mingw32-make
        shell: cmd
        run: |
          qmake m3.pro
          mingw32-make release

      - name: Deploy Qt DLLs
        shell: cmd
        run: |
          windeployqt release\m3.exe

      - name: Archive Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: m3-win-binary
          path: |
            release\*
