name: Build Windows Qt5 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2 (MSVC2019) + cache
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_msvc2019_64
          cache: true

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Release
        shell: cmd
        run: |
          qmake m3.pro
          nmake release

      - name: Deploy Qt DLLs
        shell: cmd
        run: |
          windeployqt re
